CREATE TABLE IF NOT EXISTS TRANSACTION_ENTITY (
    id INT NOT NULL AUTO_INCREMENT,
    amount INT NOT NULL,
    name VARCHAR(255),
    version VARCHAR(255),
    user_id VARCHAR(255),
    PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS TAG_ENTITY (
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(255),
    PRIMARY KEY (id)
)
CREATE TABLE IF NOT EXISTS TAGMAP_ENTITY (
    id INT NOT NULL AUTO_INCREMENT,
    transaction_id INT,
    tag_id INT,
    PRIMARY KEY (id),
    FOREIGN KEY (transaction_id) references TRANSACTION_ENTITY(id),
    FOREIGN KEY (tag_id) references TAG_ENTITY(id),
)